# Source: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
#
# SPDX-FileCopyrightText: (c) 2020 GitHub
# SPDX-License-Identifier: MIT
#
name: Publish Docs

on:
  workflow_call:
    inputs:
      lazarus-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source
    concurrency:
      group: rel-${{ inputs.lazarus-version }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Restore Lazarus packages
        id: lazarus-deb-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '/tmp/lazarus-src'
          key: lazarus-${{ inputs.lazarus-version }}-${{ runner.os }}
      - name: Install Lazarus ${{ inputs.lazarus-version }}
        run: |
          curl -sSL https://bitbucket.org/rdipardo/lazarus-orb/raw/alpha/src/scripts/install_lazarus.sh | bash
        env:
          # https://askubuntu.com/a/1421221
          NEEDRESTART_MODE: l
          DEBIAN_FRONTEND: noninteractive
          LAZARUS_VERSION: ${{ inputs.lazarus-version }}
      - name: Generate docs
        run: |
          sudo chown -R $USER /usr/share/lazarus
          docs/build
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
